### PR TITLE
fix(repository): #1603 delete repo subcollection

### PR DESCRIPTION
**Pull request by kykyk**
Done:

- add function with transaction for delete the collection
- delete repo subcollection statuses

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Sorry for my slow reply.

After testing it appears that the documents in the sub collection `statuses` do get deleted but the sub collection itself remains (although empty). I think the empty sub collection needs to also needs to get deleted

Screenshot 2019-11-18 07 58 48

**Comment by kykyk** [comment]
> Sorry for my slow reply.
> 
> After testing it appears that the documents in the sub collection `statuses` do get deleted but the sub collection itself remains (although empty). I think the empty sub collection needs to also needs to get deleted
> 
> Screenshot 2019-11-18 07 58 48

Could you provide me a chain of action you did for reproducing this bug?

**Comment by eddiejaoude** [comment]
> Could you provide me a chain of action you did for reproducing this bug?

Sure...
1. create project
2. add repo to project
3. create PR in repo on GitHub (`statuses` sub collection now has an entry)
4. delete project

All documents in the `statuses` sub collection were deleted correctly but the sub collection itself remains

**Comment by kykyk** [comment]
I checked a problem
It is not bug, the empty subcollection in firebase automatically delete through sometime

**Pull request merged**
