### PR TITLE
[#31] Google Analytics added to layout

### PR DESCRIPTION
**Pull request by eddiejaoude**

### CODE REVIEW

**Comment by brettminnie** [comment]
Once green will merge

**Comment by brettminnie** [comment]
Travis says no

**Comment by eddiejaoude** [comment]
All green now, not sure what happened. I just hit re-build on TravisCI & its fine. I will keep an eye on it.

**Comment by brettminnie** [comment]
Merged


On Mon, Mar 16, 2015 at 2:52 PM, Eddie Abou-Jaoude <notifications@github.com

**Pull request merged**
