### PR TITLE
Improve docs and fix bugs on vagrant setup

### PR DESCRIPTION
**Pull request by Netsensia**
The README.md file is now good enough to get you up-and-running properly. Fixed NFS problem that prevented apache2 from being installed. Fixed various problems that stopped the system coming up 100% accurately when following the README file. Requires VMWare.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Why `bum` for directory? What does it stand for?

**Comment by brettminnie** [comment]
Yeah, that may require a rename. Though I did chuckle

**Comment by Netsensia** [comment]
The bum was a mistake - I wanted to put the bum up a level as it was the name for my pillar directory, but I already had a directory called pillar, so I chose bum. Now deleted from PR.

**Comment by brettminnie** [comment]
Wow... Just wow ;-)

**Pull request merged**
