### PR TITLE
feat(project): #627 added support for updating og tags via meta service

### LINKED ISSUE #627: OG html tags for links on Twitter/Facebook etc
### Requirements

When sharing DashboardHub links on social media, rather than the media platform selecting the text and picture, we can specify this in the meta tags.

**UI**

- html meta tags
- on project dashboard page, use project icon, if no icon available, use dashboardhub logo

### PR DESCRIPTION
**Pull request by webkhushboo**
closes #627 

### Notes

A summary of what was achieved in this PR

- [ ] Added the Support for updating meta tags for project dashboard page.
- [ ] Updated og:title and og:image meta tags dynamically via meta service

Before
image (1)

After:
image

Twitter:
image

### CODE REVIEW

**Review by eddiejaoude — DISMISSED** [review]

**Comment by webkhushboo** [comment]
@eddiejaoude 

I am still seeing the full image . Image size should be 200*200px for square shape with description.

image

**Comment by eddiejaoude** [comment]
I updated it to be the mascot, I am not sure why the logo is appearing 🤔 . Any ideas?

**Comment by webkhushboo** [comment]
@eddiejaoude 
I understand the issue , it took from the cache. Now I verified it again after deploying on firebase
. It looks good to me :) 
Facebook:
image


Twitter:
image

**Comment by eddiejaoude** [comment]
Ok great, thank you 👍

**Review by eddiejaoude — APPROVED** [review]

**Pull request merged**
